spring.application.name=architecture


spring.datasource.url=jdbc:postgresql://localhost:5432/architecture
spring.datasource.username=postgres
spring.datasource.password=2820

spring.jpa.hibernate.ddl-auto=update